import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import AuthProvider from "@/components/auth/AuthProvider";
import FavoritesProvider from "@/components/FavoritesProvider";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import { getCurrentUser } from "@/lib/auth/session";
import { getFavoriteIds } from "@/lib/listings/favorites";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const user = await getCurrentUser();
  const favoriteIds = user ? await getFavoriteIds(user.id) : [];

  return (
    <html lang="en" className={`${inter.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider initialUser={user}>
          <FavoritesProvider initialIds={favoriteIds}>
            <Navigation />
            {children}
            <Footer />
          </FavoritesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
